spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  application:
    name: auth-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 6001

management:
  endpoint:
    health:
      enabled: true
logging:
  level:
    root: debug